services:
  - type: web
    name: nodemella-backend
    env: node
    region: oregon
    plan: free
    rootDir: Backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
